---
http_interactions:
- request:
    method: post
    uri: https://ws-use.brightpearl.com/crowdint/authorise
    body:
      encoding: UTF-8
      string: '{"apiAccountCredentials":{"emailAddress":"steven@crowdint.com","password":"Nagarrab8"}}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 09 Apr 2014 23:03:27 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 13ab2e89-9e29-4180-b663-d5b411f1e3ba
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '51'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":"6c4db151-3998-4bf6-bd23-d8f0587f3ada"}'
    http_version: 
  recorded_at: Wed, 09 Apr 2014 23:03:27 GMT
- request:
    method: post
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//integration-service/webhook
    body:
      encoding: UTF-8
      string: '{"subscribeTo"=>"product.created", "httpMethod"=>"POST", "uriTemplate"=>"http://demo.spreecommerce.com/bp_products",
        "bodyTemplate"=>"{\"accountCode\": \"${account-code}\",\"resourceType\": \"${resource-type}\",\"id\":
        \"${resource-id}\",\"lifecycle-event\": \"${lifecycle-event}\",\"full-event\":
        \"${full-event}\"}", "contentType"=>"application/json", "idSetAccepted"=>true}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 6c4db151-3998-4bf6-bd23-d8f0587f3ada
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '31820'
      Brightpearl-Requests-Remaining:
      - '197'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 09 Apr 2014 23:03:27 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 16eb5532-6c8f-4b4d-b3e7-d4b32c6ed23d
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '15'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":23}'
    http_version: 
  recorded_at: Wed, 09 Apr 2014 23:03:28 GMT
- request:
    method: post
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//integration-service/webhook
    body:
      encoding: UTF-8
      string: '{"subscribeTo"=>"product.modified", "httpMethod"=>"POST", "uriTemplate"=>"http://demo.spreecommerce.com/bp_products/${resource-id}",
        "bodyTemplate"=>"{\"accountCode\": \"${account-code}\",\"resourceType\": \"${resource-type}\",\"id\":
        \"${resource-id}\",\"lifecycle-event\": \"${lifecycle-event}\",\"full-event\":
        \"${full-event}\"}", "contentType"=>"application/json", "idSetAccepted"=>true}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 6c4db151-3998-4bf6-bd23-d8f0587f3ada
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '31203'
      Brightpearl-Requests-Remaining:
      - '196'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 09 Apr 2014 23:03:28 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 1abcddf0-6a05-4a16-a185-105da9a7e42e
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '15'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":24}'
    http_version: 
  recorded_at: Wed, 09 Apr 2014 23:03:28 GMT
- request:
    method: post
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//integration-service/webhook
    body:
      encoding: UTF-8
      string: '{"subscribeTo"=>"product.destroyed", "httpMethod"=>"DELETE", "uriTemplate"=>"http://demo.spreecommerce.com/bp_products/${resource-id}",
        "bodyTemplate"=>"", "contentType"=>"application/json", "idSetAccepted"=>true}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 6c4db151-3998-4bf6-bd23-d8f0587f3ada
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Brightpearl-Next-Throttle-Period:
      - '30537'
      Brightpearl-Requests-Remaining:
      - '195'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 09 Apr 2014 23:03:28 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 3304c64a-47ba-4522-9cf7-b1edbf337367
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '464'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"errors":[{"code":"INTC-057","message":"templateUri OR templateBody
        (for POST/PUT) must contatin the template variable ${lifecycle-event}"},{"code":"INTC-057","message":"templateUri
        OR templateBody (for POST/PUT) must contatin the template variable ${account-code}"},{"code":"INTC-057","message":"templateUri
        OR templateBody (for POST/PUT) must contatin the template variable ${resource-type}"},{"code":"INTC-062","message":"destroyed
        is not a valid lifecycle"}]}'
    http_version: 
  recorded_at: Wed, 09 Apr 2014 23:03:29 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//integration-service/webhook
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 6c4db151-3998-4bf6-bd23-d8f0587f3ada
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '30072'
      Brightpearl-Requests-Remaining:
      - '194'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 09 Apr 2014 23:03:29 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - d7e69eb2-c355-468a-844c-0c171de61089
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '778'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":23,"subscribeTo":"product.created","httpMethod":"POST","uriTemplate":"http://demo.spreecommerce.com/bp_products","bodyTemplate":"{\"accountCode\":
        \"${account-code}\",\"resourceType\": \"${resource-type}\",\"id\": \"${resource-id}\",\"lifecycle-event\":
        \"${lifecycle-event}\",\"full-event\": \"${full-event}\"}","contentType":"application/json","idSetAccepted":true},{"id":24,"subscribeTo":"product.modified","httpMethod":"POST","uriTemplate":"http://demo.spreecommerce.com/bp_products/${resource-id}","bodyTemplate":"{\"accountCode\":
        \"${account-code}\",\"resourceType\": \"${resource-type}\",\"id\": \"${resource-id}\",\"lifecycle-event\":
        \"${lifecycle-event}\",\"full-event\": \"${full-event}\"}","contentType":"application/json","idSetAccepted":true}]}'
    http_version: 
  recorded_at: Wed, 09 Apr 2014 23:03:30 GMT
recorded_with: VCR 2.9.0
