---
http_interactions:
- request:
    method: post
    uri: https://ws-use.brightpearl.com/crowdint/authorise
    body:
      encoding: UTF-8
      string: '{"apiAccountCredentials":{"emailAddress":"steven@crowdint.com","password":"Nagarrab8"}}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Tue, 08 Apr 2014 16:12:20 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - d1b9e9b6-6dbe-4ed4-9e0a-e51c598bb36e
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '51'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":"de2ffe41-b780-402c-9d5e-7ab53bc0355d"}'
    http_version: 
  recorded_at: Tue, 08 Apr 2014 16:12:21 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/product/1010
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - de2ffe41-b780-402c-9d5e-7ab53bc0355d
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '37380'
      Brightpearl-Requests-Remaining:
      - '199'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Tue, 08 Apr 2014 16:12:21 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 2d955d65-4da5-4f7c-bc2a-f3456948226d
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '896'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":1010,"brandId":75,"productTypeId":1,"identity":{"sku":"SKUawwer","barcode":""},"productGroupId":2,"stock":{"stockTracked":true,"weight":{"magnitude":10.00}},"financialDetails":{"taxable":false,"taxCode":{"id":1,"code":"Z"}},"salesChannels":[{"salesChannelName":"Brightpearl","productName":"Crowd
        produc test","productCondition":"new","categories":[{"categoryCode":"295"}],"description":{"languageCode":"en","text":"\u003cp\u003eThis
        is the largeeeeee description!!!!!!!!\u003c/p\u003e","format":"HTML_FRAGMENT"},"shortDescription":{"languageCode":"en","text":"\u003cp\u003eThis
        is the short description\u003c/p\u003e","format":"HTML_FRAGMENT"}}],"composition":{"bundle":false},"variations":[{"optionId":1,"optionName":"Color","optionValueId":3,"optionValue":"Green"}],"warehouses":{"2":{"defaultLocationId":0,"reorderLevel":20,"reorderQuantity":0}},"nominalCodeStock":"1001"}]}'
    http_version: 
  recorded_at: Tue, 08 Apr 2014 16:12:23 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/product-price/1010
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - de2ffe41-b780-402c-9d5e-7ab53bc0355d
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '36725'
      Brightpearl-Requests-Remaining:
      - '198'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Tue, 08 Apr 2014 16:12:23 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 5a76a293-9636-427f-8a4b-734c7195e42e
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '209'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"productId":1010,"priceLists":[{"priceListId":1,"currencyCode":"USD","currencyId":1,"quantityPrice":{"1":"1000.0000"}},{"priceListId":2,"currencyCode":"USD","currencyId":1,"quantityPrice":{}}]}]}'
    http_version: 
  recorded_at: Tue, 08 Apr 2014 16:12:23 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/brand/75
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - de2ffe41-b780-402c-9d5e-7ab53bc0355d
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '36227'
      Brightpearl-Requests-Remaining:
      - '197'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Tue, 08 Apr 2014 16:12:23 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 1f87f524-be1a-4dc9-8001-6a18709f56d3
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '56'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":75,"name":"Rails","description":""}]}'
    http_version: 
  recorded_at: Tue, 08 Apr 2014 16:12:24 GMT
recorded_with: VCR 2.9.0
