---
http_interactions:
- request:
    method: post
    uri: https://ws-use.brightpearl.com/crowdint/authorise
    body:
      encoding: UTF-8
      string: '{"apiAccountCredentials":{"emailAddress":"steven@crowdint.com","password":"Nagarrab8"}}'
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 02 Apr 2014 23:23:00 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 810c0ff5-aa79-4254-862d-3447c9389c1e
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '51'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":"22261eaf-f60a-4f37-85ef-c87e908a5b81"}'
    http_version:
  recorded_at: Wed, 02 Apr 2014 23:23:00 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/product/1010
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 22261eaf-f60a-4f37-85ef-c87e908a5b81
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '58759'
      Brightpearl-Requests-Remaining:
      - '199'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 02 Apr 2014 23:23:00 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - d5402525-7ccb-4861-99a7-2d52e47c5fdd
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '782'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":1010,"brandId":75,"productTypeId":1,"identity":{"sku":"SKUawwer","barcode":""},"stock":{"stockTracked":true,"weight":{"magnitude":10.00}},"financialDetails":{"taxable":false,"taxCode":{"id":1,"code":"Z"}},"salesChannels":[{"salesChannelName":"Brightpearl","productName":"Crowd
        product","productCondition":"new","categories":[{"categoryCode":"295"}],"description":{"languageCode":"en","text":"\u003cp\u003eThis
        is the largeeeeee description!!!!!!!!\u003c/p\u003e","format":"HTML_FRAGMENT"},"shortDescription":{"languageCode":"en","text":"\u003cp\u003eThis
        is the short description\u003c/p\u003e","format":"HTML_FRAGMENT"}}],"composition":{"bundle":false},"warehouses":{"2":{"defaultLocationId":0,"reorderLevel":20,"reorderQuantity":0}},"nominalCodeStock":"1001"}]}'
    http_version:
  recorded_at: Wed, 02 Apr 2014 23:23:01 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/brightpearl-category/295
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 9678093b-ff70-4c29-ba32-316bcb6756d9
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '58483'
      Brightpearl-Requests-Remaining:
      - '199'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Thu, 02 Oct 2014 00:30:00 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 0dea0e2c-701d-4cb8-af84-aeb37d650edc
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '257'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":305,"name":"Smallbatch + Wrap","parentId":0,"active":false,"createdOn":"2014-06-17T09:33:36.000+01:00","createdById":3,"updatedOn":"2014-06-17T09:33:36.000+01:00","updatedById":0,"description":{"languageCode":"en","format":"PLAINTEXT"}}]}'
    http_version:
  recorded_at: Thu, 02 Oct 2014 00:30:23 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/product-price/1010
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 22261eaf-f60a-4f37-85ef-c87e908a5b81
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '58082'
      Brightpearl-Requests-Remaining:
      - '198'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 02 Apr 2014 23:23:01 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - 2b46cde9-4784-43c2-9959-209ebc2a309e
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '209'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"productId":1010,"priceLists":[{"priceListId":1,"currencyCode":"USD","currencyId":1,"quantityPrice":{"1":"100.0000"}},{"priceListId":2,"currencyCode":"USD","currencyId":1,"quantityPrice":{"1":"1000.0000"}}]}]}'
    http_version:
  recorded_at: Wed, 02 Apr 2014 23:23:02 GMT
- request:
    method: get
    uri: https://ws-use.brightpearl.com/2.0.0/crowdint//product-service/brand/75
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.0
      Content-Type:
      - application/json
      Accept:
      - json
      Brightpearl-Auth:
      - 22261eaf-f60a-4f37-85ef-c87e908a5b81
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Brightpearl-Next-Throttle-Period:
      - '57641'
      Brightpearl-Requests-Remaining:
      - '197'
      Cache-Control:
      - no-cache, must-revalidate
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Wed, 02 Apr 2014 23:23:01 GMT
      Expires:
      - Sun, 20 Dec 1998 01:00:00 GMT
      Pragma:
      - no-cache
      Ruid:
      - daa48709-b2d5-44c4-9415-74f98aa52e16
      Server:
      - Apache-Coyote/1.1
      Content-Length:
      - '56'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"response":[{"id":75,"name":"Rails","description":""}]}'
    http_version:
  recorded_at: Wed, 02 Apr 2014 23:23:02 GMT
recorded_with: VCR 2.9.0
